url: https://stockholm.ai

collections:
  people:
    output: true
    permalink: /:collection/:title
  meetups:
    output: true
    permalink: /:collection/:title
  study-groups:
    output: true
    permalink: /:collection/:title
  companies:
    output: true
    permalink: /:collection/:title

# collections_dir: collections

defaults:
  - scope:
      path: ""
      type: people
    values:
      layout: people
  - scope:
      path: ""
      type: meetups
    values:
      layout: meetup
  - scope:
      path: ""
      type: study-groups
    values:
      layout: study-group
  - scope:
      path: ""
      type: companies
    values:
      layout: company

exclude:
  - CODEOWNERS
  - Dockerfile
  - LICENSE
  - README.md
  - TODO.md
  - "*.sh"
  - "*.conf"
  - server/

# Build settings
markdown: kramdown
permalink: /:categories/:title
